/**
 * BaZi Core Constants - Heavenly Stems and Earthly Branches
 */

import type { Gan, Zhi, Element, HiddenStem } from "./types";

// 十天干 (10 Heavenly Stems)
export const GAN: Gan[] = ["甲", "乙", "丙", "丁", "戊", "己", "庚", "辛", "壬", "癸"];

// 十二地支 (12 Earthly Branches)
export const ZHI: Zhi[] = ["子", "丑", "寅", "卯", "辰", "巳", "午", "未", "申", "酉", "戌", "亥"];

// 天干对应五行
export const GAN_ELEMENT: Record<Gan, Element> = {
  甲: "木", 乙: "木",
  丙: "火", 丁: "火",
  戊: "土", 己: "土",
  庚: "金", 辛: "金",
  壬: "水", 癸: "水",
};

// 地支对应五行
export const ZHI_ELEMENT: Record<Zhi, Element> = {
  子: "水", 丑: "土", 寅: "木", 卯: "木",
  辰: "土", 巳: "火", 午: "火", 未: "土",
  申: "金", 酉: "金", 戌: "土", 亥: "水",
};

// 地支藏干 (Hidden Stems in Branches) with weights
export const HIDDEN_STEMS: Record<Zhi, { stem: Gan; weight: number }[]> = {
  子: [{ stem: "癸", weight: 8 }],
  丑: [{ stem: "己", weight: 5 }, { stem: "癸", weight: 2 }, { stem: "辛", weight: 1 }],
  寅: [{ stem: "甲", weight: 5 }, { stem: "丙", weight: 2 }, { stem: "戊", weight: 1 }],
  卯: [{ stem: "乙", weight: 8 }],
  辰: [{ stem: "戊", weight: 5 }, { stem: "乙", weight: 2 }, { stem: "癸", weight: 1 }],
  巳: [{ stem: "丙", weight: 5 }, { stem: "戊", weight: 2 }, { stem: "庚", weight: 1 }],
  午: [{ stem: "丁", weight: 5 }, { stem: "己", weight: 3 }],
  未: [{ stem: "己", weight: 5 }, { stem: "丁", weight: 2 }, { stem: "乙", weight: 1 }],
  申: [{ stem: "庚", weight: 5 }, { stem: "壬", weight: 2 }, { stem: "戊", weight: 1 }],
  酉: [{ stem: "辛", weight: 8 }],
  戌: [{ stem: "戊", weight: 5 }, { stem: "辛", weight: 2 }, { stem: "丁", weight: 1 }],
  亥: [{ stem: "壬", weight: 5 }, { stem: "甲", weight: 3 }],
};

// 生肖 (Chinese Zodiac)
export const ZODIAC: Record<Zhi, string> = {
  子: "鼠", 丑: "牛", 寅: "虎", 卯: "兔",
  辰: "龙", 巳: "蛇", 午: "马", 未: "羊",
  申: "猴", 酉: "鸡", 戌: "狗", 亥: "猪",
};

// 五行相生相克
export const ELEMENT_RELATIONS = {
  // 相生 (generating)
  generates: {
    金: "水", 水: "木", 木: "火", 火: "土", 土: "金",
  } as Record<Element, Element>,
  // 相克 (overcoming)
  overcomes: {
    金: "木", 木: "土", 土: "水", 水: "火", 火: "金",
  } as Record<Element, Element>,
  // 被克 (overcome by)
  overcomeBy: {
    金: "火", 木: "金", 土: "木", 水: "土", 火: "水",
  } as Record<Element, Element>,
  // 生我 (generated by)
  generatedBy: {
    金: "土", 木: "水", 土: "火", 水: "金", 火: "木",
  } as Record<Element, Element>,
};

// 时辰对应时间
export const ZHI_TIME: Record<Zhi, string> = {
  子: "23:00-01:00", 丑: "01:00-03:00", 寅: "03:00-05:00", 卯: "05:00-07:00",
  辰: "07:00-09:00", 巳: "09:00-11:00", 午: "11:00-13:00", 未: "13:00-15:00",
  申: "15:00-17:00", 酉: "17:00-19:00", 戌: "19:00-21:00", 亥: "21:00-23:00",
};

// Helper functions
export function getGanIndex(gan: Gan): number {
  return GAN.indexOf(gan);
}

export function getZhiIndex(zhi: Zhi): number {
  return ZHI.indexOf(zhi);
}

export function getGanByIndex(index: number): Gan {
  return GAN[((index % 10) + 10) % 10];
}

export function getZhiByIndex(index: number): Zhi {
  return ZHI[((index % 12) + 12) % 12];
}

export function getHiddenStems(zhi: Zhi): HiddenStem[] {
  return HIDDEN_STEMS[zhi].map(h => ({ stem: h.stem, weight: h.weight }));
}

// Get hour branch from time (HH:MM format)
export function getHourBranch(time: string): Zhi {
  const [hours] = time.split(":").map(Number);

  // Map hours to branches
  if (hours >= 23 || hours < 1) return "子";
  if (hours >= 1 && hours < 3) return "丑";
  if (hours >= 3 && hours < 5) return "寅";
  if (hours >= 5 && hours < 7) return "卯";
  if (hours >= 7 && hours < 9) return "辰";
  if (hours >= 9 && hours < 11) return "巳";
  if (hours >= 11 && hours < 13) return "午";
  if (hours >= 13 && hours < 15) return "未";
  if (hours >= 15 && hours < 17) return "申";
  if (hours >= 17 && hours < 19) return "酉";
  if (hours >= 19 && hours < 21) return "戌";
  return "亥";
}
